BEGIN TRANSACTION;
CREATE TABLE `Point` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`x`	REAL NOT NULL,
	`y`	REAL NOT NULL,
	`id_figure`	INTEGER,
	`num_point`	INTEGER
);
INSERT INTO `Point` VALUES (1,0.0,0.0,1,0);
INSERT INTO `Point` VALUES (2,10.0,0.0,1,1);
INSERT INTO `Point` VALUES (3,10.0,10.0,1,2);
INSERT INTO `Point` VALUES (4,0.0,10.0,1,3);
CREATE TABLE "Length" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`value`	REAL,
	`id_figure`	INTEGER,
	`num_length`	INTEGER
);
INSERT INTO `Length` VALUES (1,10.0,1,0);
INSERT INTO `Length` VALUES (2,10.0,1,1);
INSERT INTO `Length` VALUES (3,10.0,1,2);
INSERT INTO `Length` VALUES (4,10.0,1,3);
CREATE TABLE "Figure" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`type`	TEXT NOT NULL,
	`perimeter`	REAL,
	`area`	REAL
);
INSERT INTO `Figure` VALUES (1,'Square',40.0,100.0);
COMMIT;
